language: php
php:
  - "5.6"
  - "5.5"

before_script:
  - ./tests/install-php-extension.sh
  - composer self-update
  - composer install --prefer-dist -o

script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover
  - php tools/scrutinizer/ocular.phar code-coverage:upload --format=php-clover coverage.clover